config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'players#index'

  resources :players

  resources :teams

  resources :schedules
end

app/models/concerns/player.rb
# frozen_string_literal: true

module Player
  extend ActiveSupport::Concern

  included do
    has_one :baseball_hitting_stat, as: :player, dependent: :destroy
    has_one :baseball_pitching_stat, as: :player, dependent: :destroy
    enum status: { not_active: 0, active: 1, injured_list: 2 }
  end
end

app/controllers/players_controller.rb
# frozen_string_literal: true

class PlayersController < ApplicationController
  before_action :find_player, only: [:show]

  def index
    @cpbl_player = CpblPlayerContext.new(params).perform
  end

  def show
    if @cpbl_player.pitcher?
      @player_game_logs = CpblPitchingGameLog.includes(:cpbl_schedule).where(cpbl_player: @cpbl_player)
      @player_session_game_logs = PitchingGameLogsDecorator.new(@player_game_logs)
      @player_last_7_game_logs = PitchingGameLogsDecorator.new(@player_game_logs.last(7))
      @player_last_14_game_logs = PitchingGameLogsDecorator.new(@player_game_logs.last(14))
    else
      @player_game_logs = CpblHittingGameLog.includes(:cpbl_schedule).where(cpbl_player: @cpbl_player)
      @player_session_game_logs = HittingGameLogsDecorator.new(@player_game_logs)
      @player_last_7_game_logs = HittingGameLogsDecorator.new(@player_game_logs.last(7))
      @player_last_14_game_logs = HittingGameLogsDecorator.new(@player_game_logs.last(14))
    end
  end

  private

  def find_player
    @cpbl_player = CpblPlayer.find(params[:id])
  end
end

app/views/players/shared/_hitter_table.html.erb
<table class="border-separate border border-black text-center w-full">
  <thead>
    <tr>
      <th class="bg-blue-500 text-white"></th>
      <th class="bg-blue-500 text-white">姓名</th>
      <th class="bg-blue-500 text-white">隊伍</th>
      <th class="bg-blue-500 text-white">位置</th>
      <th class="bg-blue-500 text-white"><%= link_to 'G', players_path(search_params('g')) %></th>
      <th class="bg-blue-500 text-white"><%= link_to 'AVG', players_path(search_params('avg')) %></th>
      <th class="bg-blue-500 text-white"><%= link_to 'OBP', players_path(search_params('obp')) %></th>
      <th class="bg-blue-500 text-white"><%= link_to 'SLG', players_path(search_params('slg')) %></th>
      <th class="bg-blue-500 text-white"><%= link_to 'OPS', players_path(search_params('ops')) %></th>
      <th class="bg-blue-500 text-white"><%= link_to 'AB', players_path(search_params('ab')) %></th>
      <th class="bg-blue-500 text-white"><%= link_to 'R', players_path(search_params('r')) %></th>
      <th class="bg-blue-500 text-white"><%= link_to 'H', players_path(search_params('h')) %></th>
      <th class="bg-blue-500 text-white"><%= link_to '2B', players_path(search_params('d')) %></th>
      <th class="bg-blue-500 text-white"><%= link_to '3B', players_path(search_params('t')) %></th>
      <th class="bg-blue-500 text-white"><%= link_to 'HR', players_path(search_params('hr')) %></th>
      <th class="bg-blue-500 text-white"><%= link_to 'RBI', players_path(search_params('rbi')) %></th>
      <th class="bg-blue-500 text-white"><%= link_to 'BB', players_path(search_params('bb')) %></th>
      <th class="bg-blue-500 text-white"><%= link_to 'K', players_path(search_params('so')) %></th>
      <th class="bg-blue-500 text-white"><%= link_to 'SB', players_path(search_params('sb')) %></th>
    </tr>
  </thead>
  <tbody>
    <% cpbl_hitter.each_with_index do |player, index| %>
      <tr class=<%= "#{index.even? ? 'bg-blue-100' : 'bg-blue-50'}" %>>
        <td><%= index + 1 %></td>
        <td><%= link_to player.name, player_path(player.id) %></td>
        <td><%= player.attr_team_name %></td>
        <td><%= player.code.upcase %></td>
        <td><%= player.g %></td>
        <td><%= player.avg %></td>
        <td><%= player.obp %></td>
        <td><%= player.slg %></td>
        <td><%= player.ops %></td>
        <td><%= player.ab %></td>
        <td><%= player.r %></td>
        <td><%= player.h %></td>
        <td><%= player.d %></td>
        <td><%= player.t %></td>
        <td><%= player.hr %></td>
        <td><%= player.rbi %></td>
        <td><%= player.bb %></td>
        <td><%= player.so %></td>
        <td><%= player.sb %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/players/shared/_hitting_game_log.html.erb
<table class="border-separate border border-black text-center w-full">
  <thead>
    <tr>
      <th class="bg-blue-500 text-white">日期</th>
      <th class="bg-blue-500 text-white">AB</th>
      <th class="bg-blue-500 text-white">R</th>
      <th class="bg-blue-500 text-white">H</th>
      <th class="bg-blue-500 text-white">2B</th>
      <th class="bg-blue-500 text-white">3B</th>
      <th class="bg-blue-500 text-white">HR</th>
      <th class="bg-blue-500 text-white">RBI</th>
      <th class="bg-blue-500 text-white">BB</th>
      <th class="bg-blue-500 text-white">K</th>
      <th class="bg-blue-500 text-white">SB</th>
      <th class="bg-blue-500 text-white">CS</th>
      <th class="bg-blue-500 text-white">AVG</th>
      <th class="bg-blue-500 text-white">OBP</th>
      <th class="bg-blue-500 text-white">SLG</th>
      <th class="bg-blue-500 text-white">OPS</th>
    </tr>
  </thead>
  <tbody>
    <% player_game_logs.each_with_index do |game_log, index| %>
      <tr class=<%= "#{index.even? ? 'bg-blue-100' : 'bg-blue-50'}" %>>
        <td><%= game_log.match_date.to_date.strftime('%m/%d') %></td>
        <td><%= game_log.ab %></td>
        <td><%= game_log.r %></td>
        <td><%= game_log.h %></td>
        <td><%= game_log.d %></td>
        <td><%= game_log.t %></td>
        <td><%= game_log.hr %></td>
        <td><%= game_log.rbi %></td>
        <td><%= game_log.bb %></td>
        <td><%= game_log.so %></td>
        <td><%= game_log.sb %></td>
        <td><%= game_log.cs %></td>
        <td><%= game_log.avg %></td>
        <td><%= game_log.obp %></td>
        <td><%= game_log.slg %></td>
        <td><%= game_log.ops %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/players/shared/_pitcher_table.html.erb
<table class="border-separate border border-black text-center w-full">
  <thead>
    <tr>
      <th class="bg-blue-500 text-white"></th>
      <th class="bg-blue-500 text-white">姓名</th>
      <th class="bg-blue-500 text-white">隊伍</th>
      <th class="bg-blue-500 text-white">位置</th>
      <th class="bg-blue-500 text-white"><%= link_to 'G', players_path(search_params('g')) %></th>
      <th class="bg-blue-500 text-white">GS</th>
      <th class="bg-blue-500 text-white"><%= link_to 'W', players_path(search_params('w')) %></th>
      <th class="bg-blue-500 text-white"><%= link_to 'L', players_path(search_params('l')) %></th>
      <th class="bg-blue-500 text-white"><%= link_to 'SV', players_path(search_params('sv')) %></th>
      <th class="bg-blue-500 text-white"><%= link_to 'HLD', players_path(search_params('hld')) %></th>
      <th class="bg-blue-500 text-white"><%= link_to 'IP', players_path(search_params('ip')) %></th>
      <th class="bg-blue-500 text-white"><%= link_to 'H', players_path(search_params('h')) %></th>
      <th class="bg-blue-500 text-white"><%= link_to 'R', players_path(search_params('r')) %></th>
      <th class="bg-blue-500 text-white"><%= link_to 'ER', players_path(search_params('r')) %></th>
      <th class="bg-blue-500 text-white"><%= link_to 'HR', players_path(search_params('hr')) %></th>
      <th class="bg-blue-500 text-white"><%= link_to 'BB', players_path(search_params('bb')) %></th>
      <th class="bg-blue-500 text-white"><%= link_to 'K', players_path(search_params('so')) %></th>
      <th class="bg-blue-500 text-white"><%= link_to 'ERA', players_path(search_params('era')) %></th>
      <th class="bg-blue-500 text-white"><%= link_to 'WHIP', players_path(search_params('whip')) %></th>
    </tr>
  </thead>
  <tbody>
    <% cpbl_pitcher.each_with_index do |player, index| %>
      <tr class=<%= "#{index.even? ? 'bg-blue-100' : 'bg-blue-50'}" %>>
        <td><%= index + 1 %></td>
        <td><%= link_to player.name, player_path(player.id) %></td>
        <td><%= player.attr_team_name %></td>
        <td><%= player.code.upcase %></td>
        <td><%= player.g %></td>
        <td >0</td>
        <td ><%= player.w %></td>
        <td ><%= player.l %></td>
        <td ><%= player.sv %></td>
        <td ><%= player.hld %></td>
        <td ><%= player.ip %></td>
        <td ><%= player.h %></td>
        <td ><%= player.r %></td>
        <td ><%= player.er %></td>
        <td ><%= player.hr %></td>
        <td ><%= player.bb %></td>
        <td ><%= player.so %></td>
        <td ><%= player.era %></td>
        <td ><%= player.whip %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/players/shared/_pitching_game_log.html.erb
<table class="border-separate border border-black text-center w-full">
  <thead>
    <tr>
      <th class="bg-blue-500 text-white">日期</th>
      <th class="bg-blue-500 text-white">W</th>
      <th class="bg-blue-500 text-white">L</th>
      <th class="bg-blue-500 text-white">SV</th>
      <th class="bg-blue-500 text-white">HLD</th>
      <th class="bg-blue-500 text-white">IP</th>
      <th class="bg-blue-500 text-white">H</th>
      <th class="bg-blue-500 text-white">R</th>
      <th class="bg-blue-500 text-white">ER</th>
      <th class="bg-blue-500 text-white">BB</th>
      <th class="bg-blue-500 text-white">K</th>
      <th class="bg-blue-500 text-white">ERA</th>
      <th class="bg-blue-500 text-white">WHIP</th>
    </tr>
  </thead>
  <tbody>
    <% player_game_logs.each_with_index do |game_log, index| %>
      <tr class=<%= "#{index.even? ? 'bg-blue-100' : 'bg-blue-50'}" %>>
        <td><%= game_log.match_date.to_date.strftime('%m/%d') %></td>
        <td><%= game_log.w %></td>
        <td><%= game_log.l %></td>
        <td><%= game_log.hld %></td>
        <td><%= game_log.sv %></td>
        <td><%= game_log.ip %></td>
        <td><%= game_log.h %></td>
        <td><%= game_log.r %></td>
        <td><%= game_log.er %></td>
        <td><%= game_log.bb %></td>
        <td><%= game_log.so %></td>
        <td><%= game_log.era %></td>
        <td><%= game_log.whip %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/players/shared/_recently_hitting_game_log.html.erb
<table class="border-separate border border-black text-center w-full">
  <thead>
    <tr>
      <th class="bg-blue-500 text-white">AB</th>
      <th class="bg-blue-500 text-white">R</th>
      <th class="bg-blue-500 text-white">H</th>
      <th class="bg-blue-500 text-white">2B</th>
      <th class="bg-blue-500 text-white">3B</th>
      <th class="bg-blue-500 text-white">HR</th>
      <th class="bg-blue-500 text-white">RBI</th>
      <th class="bg-blue-500 text-white">BB</th>
      <th class="bg-blue-500 text-white">K</th>
      <th class="bg-blue-500 text-white">SB</th>
      <th class="bg-blue-500 text-white">CS</th>
      <th class="bg-blue-500 text-white">AVG</th>
      <th class="bg-blue-500 text-white">OBP</th>
      <th class="bg-blue-500 text-white">SLG</th>
      <th class="bg-blue-500 text-white">OPS</th>
    </tr>
  </thead>
  <tbody>
    <tr class="bg-blue-100" >
      <td><%= player_game_logs.ab %></td>
      <td><%= player_game_logs.r %></td>
      <td><%= player_game_logs.h %></td>
      <td><%= player_game_logs.d %></td>
      <td><%= player_game_logs.t %></td>
      <td><%= player_game_logs.hr %></td>
      <td><%= player_game_logs.rbi %></td>
      <td><%= player_game_logs.bb %></td>
      <td><%= player_game_logs.so %></td>
      <td><%= player_game_logs.sb %></td>
      <td><%= player_game_logs.cs %></td>
      <td><%= player_game_logs.avg %></td>
      <td><%= player_game_logs.obp %></td>
      <td><%= player_game_logs.slg %></td>
      <td><%= player_game_logs.ops %></td>
    </tr>
  </tbody>
</table>

app/views/players/shared/_recently_pitching_game_log.html.erb
<table class="border-separate border border-black text-center w-full">
  <thead>
    <tr>
      <th class="bg-blue-500 text-white">W</th>
      <th class="bg-blue-500 text-white">L</th>
      <th class="bg-blue-500 text-white">SV</th>
      <th class="bg-blue-500 text-white">HLD</th>
      <th class="bg-blue-500 text-white">IP</th>
      <th class="bg-blue-500 text-white">H</th>
      <th class="bg-blue-500 text-white">R</th>
      <th class="bg-blue-500 text-white">ER</th>
      <th class="bg-blue-500 text-white">BB</th>
      <th class="bg-blue-500 text-white">K</th>
      <th class="bg-blue-500 text-white">ERA</th>
      <th class="bg-blue-500 text-white">WHIP</th>
    </tr>
  </thead>
  <tbody>
    <tr class="bg-blue-100">
      <td><%= player_game_logs.w %></td>
      <td><%= player_game_logs.l %></td>
      <td><%= player_game_logs.hld %></td>
      <td><%= player_game_logs.sv %></td>
      <td><%= player_game_logs.ip %></td>
      <td><%= player_game_logs.h %></td>
      <td><%= player_game_logs.r %></td>
      <td><%= player_game_logs.er %></td>
      <td><%= player_game_logs.bb %></td>
      <td><%= player_game_logs.so %></td>
      <td><%= player_game_logs.era %></td>
      <td><%= player_game_logs.whip %></td>
    </tr>
  </tbody>
</table>